version: "3.9"

services:
  api:
    container_name: api
    image: minhtruonghoang/rebt-server:0.0.2
    # build: ./
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
    ports:
      - "8080:8080"
      
    
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:6
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}

    ports:
      - "5050:5050"

volumes:
  data:
